//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R3M.Controls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/scripts/Controls/R3M.RoundPanel/round_ctr.css")]
        public string RoundPanelCss {
            get {
                return ((string)(this["RoundPanelCss"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/scripts/Controls/R3M.Pager/Pager.css")]
        public string CollectionPagerCss {
            get {
                return ((string)(this["CollectionPagerCss"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/scripts/MonoLibs/WebForm.js")]
        public string MonoWebFormJS {
            get {
                return ((string)(this["MonoWebFormJS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/scripts/Controls/R3M.MaskedInput/jquery.maskedinput-1.1.4.js")]
        public string JQueryMaskedInputJs {
            get {
                return ((string)(this["JQueryMaskedInputJs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/scripts/Controls/R3M.MaskedInput/MaskedInput.js")]
        public string MaskedInitializer {
            get {
                return ((string)(this["MaskedInitializer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/scripts/jquery.js")]
        public string JqueryPath {
            get {
                return ((string)(this["JqueryPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("round_ctr")]
        public string DefaultCssIdClass {
            get {
                return ((string)(this["DefaultCssIdClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/scripts/Controls/R3M.ConfirmMessage/jConfirmMessage.js")]
        public string ConfirmMessagePluginJs {
            get {
                return ((string)(this["ConfirmMessagePluginJs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/scripts/Controls/R3M.RoundButton/RoundButton.css")]
        public string RoundButtonCss {
            get {
                return ((string)(this["RoundButtonCss"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("button")]
        public string DefaultRoundButtonClassName {
            get {
                return ((string)(this["DefaultRoundButtonClassName"]));
            }
        }
    }
}
