//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

#endregion

namespace SEOToolSet.Entities
{
    [Serializable]
    [XmlInclude(typeof(Account))]
    [SoapInclude(typeof(Account))]
    [XmlInclude(typeof(Project))]
    [SoapInclude(typeof(Project))]
    [XmlInclude(typeof(SEOToolsetUser))]
    [SoapInclude(typeof(SEOToolsetUser))]
    /*[XmlInclude(typeof (Subscription))]
    [SoapInclude(typeof (Subscription))]*/
    public class AbstractAccount
    {
        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual Int32? MaxNumberOfUser { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual Int32? MaxNumberOfDomainUser { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual Int32? MaxNumberOfProjects { get; set; }

        public virtual string CompanyName { get; set; }

        public virtual string CompanyAddress1 { get; set; }

        public virtual string CompanyAddress2 { get; set; }

        public virtual string CompanyCity { get; set; }

        public virtual string CompanyState { get; set; }

        public virtual string CompanyZip { get; set; }

        public virtual string CreditCardNumber { get; set; }

        public virtual CreditCardType CreditCardType { get; set; }

        public virtual string CreditCardCvs { get; set; }

        public virtual string CreditCardAddress1 { get; set; }

        public virtual string CreditCardAddress2 { get; set; }

        public virtual string CreditCardCity { get; set; }

        public virtual string CreditCardZip { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual Boolean? RecurringBill { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual DateTime? CreatedDate { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual DateTime? UpdatedDate { get; set; }

        public virtual string CreatedBy { get; set; }

        public virtual string UpdatedBy { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual Boolean? Enabled { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual DateTime? AccountExpirationDate { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual DateTime? CreditCardExpiration { get; set; }

        //public virtual IList<Account> Account { get; set; }
        public virtual Account Owner { get; set; }

        public virtual IList<Project> Project { get; set; }

        public virtual IList<SEOToolsetUser> SEOToolsetUser { get; set; }

        public virtual SubscriptionLevel SubscriptionLevel { get; set; }

        /*public virtual IList<Subscription> Subscription { get; set; }*/

        public virtual String CreditCardEmail { get; set; }

        public virtual Int32? CreditCardIdCountry { get; set; }

        public virtual String CreditCardState { get; set; }

        public virtual String CreditCardCardholder { get; set; }

        public virtual String PromoCode { get; set; }

        public virtual Int32? CompanyIdCountry { get; set; }

        public virtual String CompanyPhone { get; set; }

        public virtual String CreditCardPhone { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual long? SubscriptionId { get; set; }

        public virtual DateTime? LastBillingDate{ get; set;}

        public virtual String SubscriptionLevelText { get; set; }
    }

    [Serializable]
    public class Account : AbstractAccount
    {
    }
}