//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region

using System;

#endregion

namespace SEOToolSet.Entities
{
    [Serializable]
    public class AbstractCompetitor
    {
        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        public virtual string Url { get; set; }

        public virtual string Description { get; set; }

        public virtual Project Project { get; set; }
    }

    [Serializable]
    public class Competitor : AbstractCompetitor
    {
    }
}