//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

#endregion

namespace SEOToolSet.Entities
{
    [Serializable]
    [XmlInclude(typeof (Project))]
    [SoapInclude(typeof (Project))]
    public class AbstractFrequency
    {
        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        public virtual IList<Project> Project { get; set; }
    }

    [Serializable]
    public class Frequency : AbstractFrequency
    {
    }
}