//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

#endregion

namespace SEOToolSet.Entities
{
    [Serializable]
    [XmlInclude(typeof (MonitorKeywordList))]
    [SoapInclude(typeof (MonitorKeywordList))]
    [XmlInclude(typeof (Keyword))]
    [SoapInclude(typeof (Keyword))]
    public class AbstractKeywordList
    {
        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual bool? Enabled { get; set; }

        public virtual IList<Keyword> Keyword { get; set; }

        public virtual Project Project { get; set; }

        public virtual IList<MonitorKeywordList> MonitorKeywordList { get; set; }
    }

    [Serializable]
    public class KeywordList : AbstractKeywordList
    {
    }
}