//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region

using System;
using System.Xml.Serialization;

#endregion

namespace SEOToolSet.Entities
{
    [Serializable]
    public class AbstractProjectUser
    {
        public virtual Int32 Id { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual Boolean? Enabled { get; set; }

        public virtual Project Project { get; set; }

        public virtual Role ProjectRole { get; set; }

        public virtual SEOToolsetUser SEOToolsetUser { get; set; }

        public virtual Boolean? MonitorEmails { get; set; }
    }

    [Serializable]
    public class ProjectUser : AbstractProjectUser
    {
    }
}