//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

#endregion

namespace SEOToolSet.Entities
{
    [Serializable]
    [XmlInclude(typeof (PermissionRole))]
    [SoapInclude(typeof (PermissionRole))]
    [XmlInclude(typeof (SEOToolsetUser))]
    [SoapInclude(typeof (SEOToolsetUser))]
    [XmlInclude(typeof (SubscriptionLevel))]
    [SoapInclude(typeof (SubscriptionLevel))]
    [XmlInclude(typeof (ProjectUser))]
    [SoapInclude(typeof (ProjectUser))]
    public class AbstractRole
    {
        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        public virtual string Description { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual bool? Enabled { get; set; }

        public virtual int IdRoleType { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual bool? Configurable { get; set; }

        public virtual IList<PermissionRole> PermissionRole { get; set; }

        public virtual IList<SEOToolsetUser> SEOToolsetUser { get; set; }

        public virtual IList<SubscriptionLevel> SubscriptionLevel { get; set; }

        public virtual IList<ProjectUser> ProjectUser { get; set; }
    }

    [Serializable]
    public class Role : AbstractRole
    {
    }
}