//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

#endregion

namespace SEOToolSet.Entities
{
    [Serializable]
    [XmlInclude(typeof (ProjectUser))]
    [SoapInclude(typeof (ProjectUser))]
    public class AbstractSEOToolsetUser
    {
        public virtual int Id { get; set; }

        public virtual string FirstName { get; set; }

        public virtual string LastName { get; set; }

        public virtual string Email { get; set; }

        public virtual string Address1 { get; set; }

        public virtual string Address2 { get; set; }

        public virtual string CityTown { get; set; }

        public virtual string State { get; set; }

        public virtual string Zip { get; set; }

        public virtual string Telephone { get; set; }

        public virtual string Login { get; set; }

        public virtual string Password { get; set; }

        public virtual string PasswordQuestion { get; set; }

        public virtual string PasswordAnswer { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual DateTime? LastFailedLoginDate { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual DateTime? LastActivityDate { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual DateTime? LastPasswordChangedDate { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual Boolean? IsLockedOut { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual DateTime? LockedOutDate { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual Int32? FailedPasswordAttemptCount { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual DateTime? ExpirationDate { get; set; }

        public virtual string CreatedBy { get; set; }

        public virtual string UpdatedBy { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual Boolean? Enabled { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual DateTime? CreatedDate { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual DateTime? UpdatedDate { get; set; }

        public virtual Account Account { get; set; }

        public virtual Country Country { get; set; }

        public virtual IList<ProjectUser> ProjectUser { get; set; }

        public virtual Role UserRole { get; set; }

        public virtual DateTime? LastLoginDate { get; set; }
    }

    [Serializable]
    public class SEOToolsetUser : AbstractSEOToolsetUser
    {
    }
}