//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

#endregion

namespace SEOToolSet.Entities
{
    [Serializable]
    [XmlInclude(typeof (SubscriptionDetail))]
    [SoapInclude(typeof (SubscriptionDetail))]
    public class AbstractSubscriptionProperty
    {
        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        [SoapElement(IsNullable = true)]
        public virtual bool? Enabled { get; set; }

        public virtual IList<SubscriptionDetail> SubscriptionDetail { get; set; }
    }

    [Serializable]
    public class SubscriptionProperty : AbstractSubscriptionProperty
    {
    }
}