//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEOToolSet.WebApp {
    
    
    public partial class Dummy {
        
        /// <summary>
        /// WebUserControl0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.PageTitle WebUserControl0;
        
        /// <summary>
        /// CostConversion1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.Controls.CostConversion CostConversion1;
        
        /// <summary>
        /// hlnkDoCalculate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::R3M.Controls.HyperLinkRound hlnkDoCalculate;
    }
}
