//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEOToolSet.WebApp {
    
    
    public partial class RankingMonitorReports {
        
        /// <summary>
        /// IncludeFile11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.Controls.IncludeFile IncludeFile11;
        
        /// <summary>
        /// PageTitle1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.PageTitle PageTitle1;
        
        /// <summary>
        /// IncludeFile2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.Controls.IncludeFile IncludeFile2;
        
        /// <summary>
        /// IncludeFile4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.Controls.IncludeFile IncludeFile4;
        
        /// <summary>
        /// IncludeFile1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.Controls.IncludeFile IncludeFile1;
        
        /// <summary>
        /// IncludeFile7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.Controls.IncludeFile IncludeFile7;
        
        /// <summary>
        /// IncludeFile3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.Controls.IncludeFile IncludeFile3;
        
        /// <summary>
        /// RoundPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::R3M.Controls.RoundPanel RoundPanel1;
        
        /// <summary>
        /// LocalizeReportSelection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize LocalizeReportSelection;
        
        /// <summary>
        /// LocalizeReportToView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize LocalizeReportToView;
        
        /// <summary>
        /// LocalizeReportToCompare control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize LocalizeReportToCompare;
        
        /// <summary>
        /// LocalizeSearchEnginesToDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize LocalizeSearchEnginesToDisplay;
        
        /// <summary>
        /// SearchEnginesRenderer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.ArrayRenderer SearchEnginesRenderer;
        
        /// <summary>
        /// LocalizeSearchEngineToAdd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize LocalizeSearchEngineToAdd;
        
        /// <summary>
        /// addEngineLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::R3M.Controls.HyperLinkRound addEngineLink;
        
        /// <summary>
        /// ViewReportButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::R3M.Controls.HyperLinkRound ViewReportButton;
        
        /// <summary>
        /// RoundPanel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::R3M.Controls.RoundPanel RoundPanel3;
        
        /// <summary>
        /// ArrayRenderer1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.ArrayRenderer ArrayRenderer1;
        
        /// <summary>
        /// RoundPanelReportDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::R3M.Controls.RoundPanel RoundPanelReportDetail;
        
        /// <summary>
        /// LocalizeReportDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize LocalizeReportDetail;
        
        /// <summary>
        /// ArrayRenderer2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SEOToolSet.WebApp.ArrayRenderer ArrayRenderer2;
        
        /// <summary>
        /// LocalizeDetailedReportLegend control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize LocalizeDetailedReportLegend;
        
        /// <summary>
        /// HyperLinkPrintReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::R3M.Controls.HyperLinkRound HyperLinkPrintReport;
        
        /// <summary>
        /// LinkButtonPrintToPDF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::R3M.Controls.LinkButtonRound LinkButtonPrintToPDF;
        
        /// <summary>
        /// LocalizeCurrentView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize LocalizeCurrentView;
        
        /// <summary>
        /// LocalizeFullData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize LocalizeFullData;
        
        /// <summary>
        /// LinkButtonRound1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::R3M.Controls.LinkButtonRound LinkButtonRound1;
        
        /// <summary>
        /// LinkButtonRound2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::R3M.Controls.LinkButtonRound LinkButtonRound2;
        
        /// <summary>
        /// CSVData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField CSVData;
        
        /// <summary>
        /// FileNameHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField FileNameHidden;
    }
}
