//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonTerms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonTerms() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CommonTerms", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为所有资源查找重写当前线程的 CurrentUICulture 属性，
        ///   方法是使用此强类型资源类。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Address 的本地化字符串。
        /// </summary>
        internal static string AccountAddress {
            get {
                return ResourceManager.GetString("AccountAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Information 的本地化字符串。
        /// </summary>
        internal static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Name 的本地化字符串。
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Profile 的本地化字符串。
        /// </summary>
        internal static string AccountProfile {
            get {
                return ResourceManager.GetString("AccountProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Projects 的本地化字符串。
        /// </summary>
        internal static string AccountProjects {
            get {
                return ResourceManager.GetString("AccountProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Users 的本地化字符串。
        /// </summary>
        internal static string AccountUsers {
            get {
                return ResourceManager.GetString("AccountUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This action cannot be undone 的本地化字符串。
        /// </summary>
        internal static string ActionCouldNotBeUndone {
            get {
                return ResourceManager.GetString("ActionCouldNotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activity 的本地化字符串。
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Competitor 的本地化字符串。
        /// </summary>
        internal static string AddCompetitor {
            get {
                return ResourceManager.GetString("AddCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Alias 的本地化字符串。
        /// </summary>
        internal static string AddDomain {
            get {
                return ResourceManager.GetString("AddDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Keyword 的本地化字符串。
        /// </summary>
        internal static string AddKeyword {
            get {
                return ResourceManager.GetString("AddKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Keyword List 的本地化字符串。
        /// </summary>
        internal static string AddKeywordList {
            get {
                return ResourceManager.GetString("AddKeywordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Project 的本地化字符串。
        /// </summary>
        internal static string AddNewProject {
            get {
                return ResourceManager.GetString("AddNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The address is required 的本地化字符串。
        /// </summary>
        internal static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        internal static string AdvancedOptions {
            get {
                return ResourceManager.GetString("AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alias Domains 的本地化字符串。
        /// </summary>
        internal static string AliasDomains {
            get {
                return ResourceManager.GetString("AliasDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AllInTitle 的本地化字符串。
        /// </summary>
        internal static string AllInTitle {
            get {
                return ResourceManager.GetString("AllInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyze 的本地化字符串。
        /// </summary>
        internal static string Analyze {
            get {
                return ResourceManager.GetString("Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyze Page: 的本地化字符串。
        /// </summary>
        internal static string AnalyzePage {
            get {
                return ResourceManager.GetString("AnalyzePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 and all the keywords that belong to it 的本地化字符串。
        /// </summary>
        internal static string AndItsKeywords {
            get {
                return ResourceManager.GetString("AndItsKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEOToolSet Application 的本地化字符串。
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Version 的本地化字符串。
        /// </summary>
        internal static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Billing Information 的本地化字符串。
        /// </summary>
        internal static string BillingInformation {
            get {
                return ResourceManager.GetString("BillingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name on Card 的本地化字符串。
        /// </summary>
        internal static string CardholderName {
            get {
                return ResourceManager.GetString("CardholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The cardholder name is required 的本地化字符串。
        /// </summary>
        internal static string CardholderNameRequired {
            get {
                return ResourceManager.GetString("CardholderNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment Type 的本地化字符串。
        /// </summary>
        internal static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Check All ] 的本地化字符串。
        /// </summary>
        internal static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check All 的本地化字符串。
        /// </summary>
        internal static string CheckAllWithoutBrackets {
            get {
                return ResourceManager.GetString("CheckAllWithoutBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Check None ] 的本地化字符串。
        /// </summary>
        internal static string CheckNone {
            get {
                return ResourceManager.GetString("CheckNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose 的本地化字符串。
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose a element 的本地化字符串。
        /// </summary>
        internal static string ChooseAnItem {
            get {
                return ResourceManager.GetString("ChooseAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose language 的本地化字符串。
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 City/Town 的本地化字符串。
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The city is required 的本地化字符串。
        /// </summary>
        internal static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Form 的本地化字符串。
        /// </summary>
        internal static string ClearForm {
            get {
                return ResourceManager.GetString("ClearForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client Name 的本地化字符串。
        /// </summary>
        internal static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client name is required 的本地化字符串。
        /// </summary>
        internal static string ClientNameRequired {
            get {
                return ResourceManager.GetString("ClientNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Collapse All ] 的本地化字符串。
        /// </summary>
        internal static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Competitor 的本地化字符串。
        /// </summary>
        internal static string Competitor {
            get {
                return ResourceManager.GetString("Competitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Competitor Domains 的本地化字符串。
        /// </summary>
        internal static string Competitors {
            get {
                return ResourceManager.GetString("Competitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact E-mail 的本地化字符串。
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Name 的本地化字符串。
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Phone 的本地化字符串。
        /// </summary>
        internal static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Country 的本地化字符串。
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The country is required 的本地化字符串。
        /// </summary>
        internal static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPC 的本地化字符串。
        /// </summary>
        internal static string CPC {
            get {
                return ResourceManager.GetString("CPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The address for the credit card is required 的本地化字符串。
        /// </summary>
        internal static string CreditCardAddressRequired {
            get {
                return ResourceManager.GetString("CreditCardAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The city for the credit card is required 的本地化字符串。
        /// </summary>
        internal static string CreditCardCityRequired {
            get {
                return ResourceManager.GetString("CreditCardCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The country for the credit card is required 的本地化字符串。
        /// </summary>
        internal static string CreditCardCountryRequired {
            get {
                return ResourceManager.GetString("CreditCardCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The expiration date for the credit card is not valid 的本地化字符串。
        /// </summary>
        internal static string CreditCardExpirationDateNotValid {
            get {
                return ResourceManager.GetString("CreditCardExpirationDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The expiration date for the credit card is required 的本地化字符串。
        /// </summary>
        internal static string CreditCardExpirationDateRequired {
            get {
                return ResourceManager.GetString("CreditCardExpirationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name for the credit card is required 的本地化字符串。
        /// </summary>
        internal static string CreditCardNameRequired {
            get {
                return ResourceManager.GetString("CreditCardNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Card Number 的本地化字符串。
        /// </summary>
        internal static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The credit card is not valid 的本地化字符串。
        /// </summary>
        internal static string CreditCardNumberNotValid {
            get {
                return ResourceManager.GetString("CreditCardNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The credit card number is required 的本地化字符串。
        /// </summary>
        internal static string CreditCardNumberRequired {
            get {
                return ResourceManager.GetString("CreditCardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The state for the credit card address is required 的本地化字符串。
        /// </summary>
        internal static string CreditCardStateRequired {
            get {
                return ResourceManager.GetString("CreditCardStateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The credit card type is required 的本地化字符串。
        /// </summary>
        internal static string CreditCardTypeRequired {
            get {
                return ResourceManager.GetString("CreditCardTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The credit card zip code is required 的本地化字符串。
        /// </summary>
        internal static string CreditCardZipRequired {
            get {
                return ResourceManager.GetString("CreditCardZipRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CVS 的本地化字符串。
        /// </summary>
        internal static string CVS {
            get {
                return ResourceManager.GetString("CVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CVS code is required 的本地化字符串。
        /// </summary>
        internal static string CVSRequired {
            get {
                return ResourceManager.GetString("CVSRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete {0}? 的本地化字符串。
        /// </summary>
        internal static string DeleteItemConfirm {
            get {
                return ResourceManager.GetString("DeleteItemConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have the required permissions for this tool. If this is an error, please contact support at support@seotoolset.com. You may also upgrade your account at the Manage Account Screen. 的本地化字符串。
        /// </summary>
        internal static string DenyAccess {
            get {
                return ResourceManager.GetString("DenyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access is denied 的本地化字符串。
        /// </summary>
        internal static string DenyAccessTitle {
            get {
                return ResourceManager.GetString("DenyAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have permission to access this Page 的本地化字符串。
        /// </summary>
        internal static string DenyAccessToPage {
            get {
                return ResourceManager.GetString("DenyAccessToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p&gt;Registered Technology and Format Copyright © 2008 Bruce Clay, Inc. All rights reserverd.&lt;/p&gt;&lt;p&gt;All trademarks are the property of their respective holders – all rights reserved&lt;/p&gt; 的本地化字符串。
        /// </summary>
        internal static string DisclaimerSpeech {
            get {
                return ResourceManager.GetString("DisclaimerSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain 的本地化字符串。
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The domain is not valid 的本地化字符串。
        /// </summary>
        internal static string DomainNotValid {
            get {
                return ResourceManager.GetString("DomainNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The domain is Required 的本地化字符串。
        /// </summary>
        internal static string DomainRequired {
            get {
                return ResourceManager.GetString("DomainRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Account Information 的本地化字符串。
        /// </summary>
        internal static string EditAccountInformation {
            get {
                return ResourceManager.GetString("EditAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit URL 的本地化字符串。
        /// </summary>
        internal static string EditURL {
            get {
                return ResourceManager.GetString("EditURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit User Information 的本地化字符串。
        /// </summary>
        internal static string EditUserInformation {
            get {
                return ResourceManager.GetString("EditUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element 的本地化字符串。
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elements 的本地化字符串。
        /// </summary>
        internal static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The e-mail is not valid 的本地化字符串。
        /// </summary>
        internal static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The e-mail is required 的本地化字符串。
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engines 的本地化字符串。
        /// </summary>
        internal static string Engines {
            get {
                return ResourceManager.GetString("Engines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a different address 的本地化字符串。
        /// </summary>
        internal static string EnterDifferentAddressCommand {
            get {
                return ResourceManager.GetString("EnterDifferentAddressCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ooops! Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Expand All ] 的本地化字符串。
        /// </summary>
        internal static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expiration Date 的本地化字符串。
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Name 的本地化字符串。
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The first name is required 的本地化字符串。
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Settings 的本地化字符串。
        /// </summary>
        internal static string FontSettings {
            get {
                return ResourceManager.GetString("FontSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google Results 的本地化字符串。
        /// </summary>
        internal static string GoogleResults {
            get {
                return ResourceManager.GetString("GoogleResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help &amp;amp; Documentation 的本地化字符串。
        /// </summary>
        internal static string HelpAndDocumentation {
            get {
                return ResourceManager.GetString("HelpAndDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inbound Links 的本地化字符串。
        /// </summary>
        internal static string InboundLinks {
            get {
                return ResourceManager.GetString("InboundLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 keyword 的本地化字符串。
        /// </summary>
        internal static string keyword {
            get {
                return ResourceManager.GetString("keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyword List 的本地化字符串。
        /// </summary>
        internal static string KeywordList {
            get {
                return ResourceManager.GetString("KeywordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyword Lists 的本地化字符串。
        /// </summary>
        internal static string KeywordLists {
            get {
                return ResourceManager.GetString("KeywordLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyword Ranking Distribution 的本地化字符串。
        /// </summary>
        internal static string KeywordRankingDistribution {
            get {
                return ResourceManager.GetString("KeywordRankingDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keywords 的本地化字符串。
        /// </summary>
        internal static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Monitor Run 的本地化字符串。
        /// </summary>
        internal static string LastMonitorRun {
            get {
                return ResourceManager.GetString("LastMonitorRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Name 的本地化字符串。
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The last name is required 的本地化字符串。
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch 的本地化字符串。
        /// </summary>
        internal static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legal 的本地化字符串。
        /// </summary>
        internal static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Links 的本地化字符串。
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The login name is required 的本地化字符串。
        /// </summary>
        internal static string LoginNameRequired {
            get {
                return ResourceManager.GetString("LoginNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Keywords 的本地化字符串。
        /// </summary>
        internal static string ManageKeywords {
            get {
                return ResourceManager.GetString("ManageKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Project 的本地化字符串。
        /// </summary>
        internal static string ManageProject {
            get {
                return ResourceManager.GetString("ManageProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Users 的本地化字符串。
        /// </summary>
        internal static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor 的本地化字符串。
        /// </summary>
        internal static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi Page Analyzer 的本地化字符串。
        /// </summary>
        internal static string MultiPageKDA {
            get {
                return ResourceManager.GetString("MultiPageKDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name is required 的本地化字符串。
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Address 的本地化字符串。
        /// </summary>
        internal static string NewAddress {
            get {
                return ResourceManager.GetString("NewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Project 的本地化字符串。
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New User 的本地化字符串。
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Active Projects 的本地化字符串。
        /// </summary>
        internal static string NoProjectsActive {
            get {
                return ResourceManager.GetString("NoProjectsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no projects in this account 的本地化字符串。
        /// </summary>
        internal static string NoProjectsFound {
            get {
                return ResourceManager.GetString("NoProjectsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No User Matched 的本地化字符串。
        /// </summary>
        internal static string NoUserMatched {
            get {
                return ResourceManager.GetString("NoUserMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no users in this account 的本地化字符串。
        /// </summary>
        internal static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimized Pages 的本地化字符串。
        /// </summary>
        internal static string OptimizedPages {
            get {
                return ResourceManager.GetString("OptimizedPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comparison Page Analyzer 的本地化字符串。
        /// </summary>
        internal static string PageComparison {
            get {
                return ResourceManager.GetString("PageComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Application is not current available, please try again later 的本地化字符串。
        /// </summary>
        internal static string PageErrorMessage {
            get {
                return ResourceManager.GetString("PageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Information Tool 的本地化字符串。
        /// </summary>
        internal static string PageInformationTool {
            get {
                return ResourceManager.GetString("PageInformationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your user do not have the required permissions to view the page. Try with another user 的本地化字符串。
        /// </summary>
        internal static string PageNotAllowed {
            get {
                return ResourceManager.GetString("PageNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageRank 的本地化字符串。
        /// </summary>
        internal static string PageRank {
            get {
                return ResourceManager.GetString("PageRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pages 的本地化字符串。
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pages Indexed 的本地化字符串。
        /// </summary>
        internal static string PagesIndexed {
            get {
                return ResourceManager.GetString("PagesIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The passwords do not coincide 的本地化字符串。
        /// </summary>
        internal static string PasswordNotCoincide {
            get {
                return ResourceManager.GetString("PasswordNotCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The password is not valid. 的本地化字符串。
        /// </summary>
        internal static string PasswordNotValid {
            get {
                return ResourceManager.GetString("PasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The password is required 的本地化字符串。
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paypal 的本地化字符串。
        /// </summary>
        internal static string Paypal {
            get {
                return ResourceManager.GetString("Paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4} 的本地化字符串。
        /// </summary>
        internal static string PhoneRegexValidation {
            get {
                return ResourceManager.GetString("PhoneRegexValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \d{5}(-\d{4})? 的本地化字符串。
        /// </summary>
        internal static string PostalCodeRegexValidation {
            get {
                return ResourceManager.GetString("PostalCodeRegexValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Privacy Statement 的本地化字符串。
        /// </summary>
        internal static string PrivacyStatement {
            get {
                return ResourceManager.GetString("PrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proceed 的本地化字符串。
        /// </summary>
        internal static string Proceed {
            get {
                return ResourceManager.GetString("Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing 的本地化字符串。
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Dashboard 的本地化字符串。
        /// </summary>
        internal static string ProjectDashboard {
            get {
                return ResourceManager.GetString("ProjectDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Information 的本地化字符串。
        /// </summary>
        internal static string ProjectInformation {
            get {
                return ResourceManager.GetString("ProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The project name is Required 的本地化字符串。
        /// </summary>
        internal static string ProjectNameRequired {
            get {
                return ResourceManager.GetString("ProjectNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Role 的本地化字符串。
        /// </summary>
        internal static string ProjectRole {
            get {
                return ResourceManager.GetString("ProjectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Settings 的本地化字符串。
        /// </summary>
        internal static string ProjectSettings {
            get {
                return ResourceManager.GetString("ProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Servers 的本地化字符串。
        /// </summary>
        internal static string ProxyServers {
            get {
                return ResourceManager.GetString("ProxyServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Stats 的本地化字符串。
        /// </summary>
        internal static string QuickStats {
            get {
                return ResourceManager.GetString("QuickStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ranking 的本地化字符串。
        /// </summary>
        internal static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the item from this list 的本地化字符串。
        /// </summary>
        internal static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the user from the current project 的本地化字符串。
        /// </summary>
        internal static string RemoveUserFromProject {
            get {
                return ResourceManager.GetString("RemoveUserFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reports 的本地化字符串。
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Defaults 的本地化字符串。
        /// </summary>
        internal static string RestoreDefaults {
            get {
                return ResourceManager.GetString("RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retype Password 的本地化字符串。
        /// </summary>
        internal static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have to re-type the password 的本地化字符串。
        /// </summary>
        internal static string RetypePasswordRequired {
            get {
                return ResourceManager.GetString("RetypePasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The role is required 的本地化字符串。
        /// </summary>
        internal static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Engine 的本地化字符串。
        /// </summary>
        internal static string SearchEngine {
            get {
                return ResourceManager.GetString("SearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Engines 的本地化字符串。
        /// </summary>
        internal static string SearchEngines {
            get {
                return ResourceManager.GetString("SearchEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an element 的本地化字符串。
        /// </summary>
        internal static string SelectAnElement {
            get {
                return ResourceManager.GetString("SelectAnElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEOToolSet &amp;reg; 的本地化字符串。
        /// </summary>
        internal static string SeoToolSetRegistered {
            get {
                return ResourceManager.GetString("SeoToolSetRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (0|1)\d/(0|1|2|3)\d/\d\d 的本地化字符串。
        /// </summary>
        internal static string ShortDateRegexValidation {
            get {
                return ResourceManager.GetString("ShortDateRegexValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show All 的本地化字符串。
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Reports 的本地化字符串。
        /// </summary>
        internal static string ShowReports {
            get {
                return ResourceManager.GetString("ShowReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Selected 的本地化字符串。
        /// </summary>
        internal static string ShowSelected {
            get {
                return ResourceManager.GetString("ShowSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in 的本地化字符串。
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign out 的本地化字符串。
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign up 的本地化字符串。
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Page Analyzer 的本地化字符串。
        /// </summary>
        internal static string SinglePageKDA {
            get {
                return ResourceManager.GetString("SinglePageKDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site Checker 的本地化字符串。
        /// </summary>
        internal static string SiteChecker {
            get {
                return ResourceManager.GetString("SiteChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site Information 的本地化字符串。
        /// </summary>
        internal static string SiteInformation {
            get {
                return ResourceManager.GetString("SiteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This page is under construction 的本地化字符串。
        /// </summary>
        internal static string SiteUnderConstruction {
            get {
                return ResourceManager.GetString("SiteUnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The state is required 的本地化字符串。
        /// </summary>
        internal static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscription Level 的本地化字符串。
        /// </summary>
        internal static string SubscriptionLevel {
            get {
                return ResourceManager.GetString("SubscriptionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support 的本地化字符串。
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone Number 的本地化字符串。
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the competitor 的本地化字符串。
        /// </summary>
        internal static string TheCompetitor {
            get {
                return ResourceManager.GetString("TheCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the keyword 的本地化字符串。
        /// </summary>
        internal static string TheKeyword {
            get {
                return ResourceManager.GetString("TheKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the keyword list 的本地化字符串。
        /// </summary>
        internal static string TheKeywordList {
            get {
                return ResourceManager.GetString("TheKeywordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the selected projects 的本地化字符串。
        /// </summary>
        internal static string TheSelectedProjects {
            get {
                return ResourceManager.GetString("TheSelectedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the selected users 的本地化字符串。
        /// </summary>
        internal static string TheSelectedUsers {
            get {
                return ResourceManager.GetString("TheSelectedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 10% 的本地化字符串。
        /// </summary>
        internal static string TopTenPercent {
            get {
                return ResourceManager.GetString("TopTenPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Uncheck All ] 的本地化字符串。
        /// </summary>
        internal static string UncheckAll {
            get {
                return ResourceManager.GetString("UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uncheck All 的本地化字符串。
        /// </summary>
        internal static string UncheckAllWithoutBrackets {
            get {
                return ResourceManager.GetString("UncheckAllWithoutBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload File 的本地化字符串。
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url &amp;amp; Keywords 的本地化字符串。
        /// </summary>
        internal static string UrlAndKeywords {
            get {
                return ResourceManager.GetString("UrlAndKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url to analyze 的本地化字符串。
        /// </summary>
        internal static string UrlToAnalyze {
            get {
                return ResourceManager.GetString("UrlToAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User&apos;s Address 的本地化字符串。
        /// </summary>
        internal static string UserAddress {
            get {
                return ResourceManager.GetString("UserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Profile 的本地化字符串。
        /// </summary>
        internal static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Role 的本地化字符串。
        /// </summary>
        internal static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user role is required 的本地化字符串。
        /// </summary>
        internal static string UserRoleRequired {
            get {
                return ResourceManager.GetString("UserRoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome {0} 的本地化字符串。
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        internal static string WelcomeAnonymous {
            get {
                return ResourceManager.GetString("WelcomeAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zip 的本地化字符串。
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The zip code is required 的本地化字符串。
        /// </summary>
        internal static string ZipRequired {
            get {
                return ResourceManager.GetString("ZipRequired", resourceCulture);
            }
        }
    }
}
