//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DialogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DialogMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Project.
        /// </summary>
        internal static string AddNewProject {
            get {
                return ResourceManager.GetString("AddNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to navigate away from this page?.
        /// </summary>
        internal static string AreYouSureWantToLeave {
            get {
                return ResourceManager.GetString("AreYouSureWantToLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like assistance, please&lt;br /&gt; &lt;a target=&quot;_blank&quot; href=&quot;http://www.seotoolset.com/support/help.html&quot;&gt; contact SEOToolSet&amp;#174; Technical Support.&lt;/a&gt;.
        /// </summary>
        internal static string AssistanceMessage {
            get {
                return ResourceManager.GetString("AssistanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Connection Issue.
        /// </summary>
        internal static string ClientConnectionIssueTitle {
            get {
                return ResourceManager.GetString("ClientConnectionIssueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Exit.
        /// </summary>
        internal static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Found.
        /// </summary>
        internal static string DataNotFoundTitle {
            get {
                return ResourceManager.GetString("DataNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error at processing the operation. Check the required steps to perform the action you want to do.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can configure the Ranking Monitor, keywords must be set up for the project. You can choose to manage keywords for the project now, or click Back to return to the previous page..
        /// </summary>
        internal static string KeywordsNotSpecified {
            get {
                return ResourceManager.GetString("KeywordsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords Not Specified.
        /// </summary>
        internal static string KeywordsNotSpecifiedTitle {
            get {
                return ResourceManager.GetString("KeywordsNotSpecifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Page.
        /// </summary>
        internal static string LeavePageButtonText {
            get {
                return ResourceManager.GetString("LeavePageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Keywords.
        /// </summary>
        internal static string ManageKeywords {
            get {
                return ResourceManager.GetString("ManageKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one keyword list to monitor..
        /// </summary>
        internal static string NoKeywordSelectedToMonitor {
            get {
                return ResourceManager.GetString("NoKeywordSelectedToMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to any active projects. Please select Add New Project to create one, or contact your account administrator to gain access to an existing project..
        /// </summary>
        internal static string NoProjectActive {
            get {
                return ResourceManager.GetString("NoProjectActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile service failed with message: {0}.
        /// </summary>
        internal static string ProfileServiceFailed {
            get {
                return ResourceManager.GetString("ProfileServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Not Selected.
        /// </summary>
        internal static string ProjectSelectionError {
            get {
                return ResourceManager.GetString("ProjectSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion code entered is valid for existing accounts only.
        /// </summary>
        internal static string PromoCodeAccountTypeOnlyExisting {
            get {
                return ResourceManager.GetString("PromoCodeAccountTypeOnlyExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion code entered is valid for new accounts only.
        /// </summary>
        internal static string PromoCodeAccountTypeOnlyNew {
            get {
                return ResourceManager.GetString("PromoCodeAccountTypeOnlyNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion code entered has expired.
        /// </summary>
        internal static string PromoCodeExpired {
            get {
                return ResourceManager.GetString("PromoCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion code has been used maximum number of times.
        /// </summary>
        internal static string PromoCodeMaxUseExceeded {
            get {
                return ResourceManager.GetString("PromoCodeMaxUseExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion code entered is not valid.
        /// </summary>
        internal static string PromoCodeNotValid {
            get {
                return ResourceManager.GetString("PromoCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion code entered will not be valid until {0}.
        /// </summary>
        internal static string PromoCodeNotYetValid {
            get {
                return ResourceManager.GetString("PromoCodeNotYetValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ranking Monitor reports have been run for the selected project. To check when the next Ranking Monitor is scheduled to be run or to run one manually, you can view the Ranking Monitor Dashboard.
        /// </summary>
        internal static string RankingReportsNotFound {
            get {
                return ResourceManager.GetString("RankingReportsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have not been saved for this page. Are you sure you want to discard your changes and restore the system default settings?.
        /// </summary>
        internal static string RestaureDefaultWithUnsavedChanges {
            get {
                return ResourceManager.GetString("RestaureDefaultWithUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Dashboard.
        /// </summary>
        internal static string ShowDashboard {
            get {
                return ResourceManager.GetString("ShowDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay on Page.
        /// </summary>
        internal static string StayOnPageButtonText {
            get {
                return ResourceManager.GetString("StayOnPageButtonText", resourceCulture);
            }
        }
    }
}
