//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JavascriptMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JavascriptMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.JavascriptMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort Reports loading?.
        /// </summary>
        internal static string AbortReportsLoadingQuestion {
            get {
                return ResourceManager.GetString("AbortReportsLoadingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SEOToolSet.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose another name for the account. The name is used by another account.
        /// </summary>
        internal static string AccountNameNotUnique {
            get {
                return ResourceManager.GetString("AccountNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Project.
        /// </summary>
        internal static string AddNewProject {
            get {
                return ResourceManager.GetString("AddNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreSureQuestion {
            get {
                return ResourceManager.GetString("AreSureQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like assistance, please&lt;br /&gt; &lt;a target=&apos;_blank&apos; href=&apos;http://www.seotoolset.com/support/help.html&apos;&gt; contact SEOToolSet&amp;#174; Technical Support.&lt;/a&gt;.
        /// </summary>
        internal static string AssistanceMessage {
            get {
                return ResourceManager.GetString("AssistanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, the async request failed, please refresh the page and try again.
        /// </summary>
        internal static string AsyncRequestFailed {
            get {
                return ResourceManager.GetString("AsyncRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one Project to perform this action.
        /// </summary>
        internal static string AtLeastOneProjectSelected {
            get {
                return ResourceManager.GetString("AtLeastOneProjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken link.
        /// </summary>
        internal static string BrokenLink {
            get {
                return ResourceManager.GetString("BrokenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard your changes to the page?.
        /// </summary>
        internal static string CancelConfirmation {
            get {
                return ResourceManager.GetString("CancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Check All ].
        /// </summary>
        internal static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Check None ].
        /// </summary>
        internal static string CheckNone {
            get {
                return ResourceManager.GetString("CheckNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseCommand {
            get {
                return ResourceManager.GetString("CloseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string DecimalSeparator {
            get {
                return ResourceManager.GetString("DecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string DeleteConfirmationQuestion {
            get {
                return ResourceManager.GetString("DeleteConfirmationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the entire KeywordList this action cannot be undone?.
        /// </summary>
        internal static string DeleteConfirmationQuestionKeywordList {
            get {
                return ResourceManager.GetString("DeleteConfirmationQuestionKeywordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        internal static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit URL.
        /// </summary>
        internal static string EditURL {
            get {
                return ResourceManager.GetString("EditURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is used by another user.
        /// </summary>
        internal static string EmailNotUnique {
            get {
                return ResourceManager.GetString("EmailNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors were found.
        /// </summary>
        internal static string ErrorFound {
            get {
                return ResourceManager.GetString("ErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... Error while trying to receive the report data..
        /// </summary>
        internal static string ErrorInLine {
            get {
                return ResourceManager.GetString("ErrorInLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string FrequencyMonth {
            get {
                return ResourceManager.GetString("FrequencyMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Two Weeks.
        /// </summary>
        internal static string FrequencyTwoWeeks {
            get {
                return ResourceManager.GetString("FrequencyTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string FrequencyWeek {
            get {
                return ResourceManager.GetString("FrequencyWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Hide ].
        /// </summary>
        internal static string HideCommand {
            get {
                return ResourceManager.GetString("HideCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Required.
        /// </summary>
        internal static string InputRequired {
            get {
                return ResourceManager.GetString("InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected.
        /// </summary>
        internal static string ItemsSelected {
            get {
                return ResourceManager.GetString("ItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword List.
        /// </summary>
        internal static string KeywordList {
            get {
                return ResourceManager.GetString("KeywordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opps the KeywordList could not be deleted, try to delete the Keywords first.
        /// </summary>
        internal static string KeywordListCannotBeDeleted {
            get {
                return ResourceManager.GetString("KeywordListCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login name is used by another user.
        /// </summary>
        internal static string LoginNameNotUnique {
            get {
                return ResourceManager.GetString("LoginNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issues found.
        /// </summary>
        internal static string NoIssuesFound {
            get {
                return ResourceManager.GetString("NoIssuesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one {0} at least.
        /// </summary>
        internal static string NoItemSelected {
            get {
                return ResourceManager.GetString("NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose at least one report.
        /// </summary>
        internal static string NoReportSelected {
            get {
                return ResourceManager.GetString("NoReportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the page is reloaded.
        /// </summary>
        internal static string PageReloading {
            get {
                return ResourceManager.GetString("PageReloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm.
        /// </summary>
        internal static string PleaseConfirm {
            get {
                return ResourceManager.GetString("PleaseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project could not be changed.
        /// </summary>
        internal static string ProjectCouldNotBeChanged {
            get {
                return ResourceManager.GetString("ProjectCouldNotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project cannot be deleted. There was a problem in the operation..
        /// </summary>
        internal static string ProjectDeletionError {
            get {
                return ResourceManager.GetString("ProjectDeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Selection Error.
        /// </summary>
        internal static string ProjectSelectionError {
            get {
                return ResourceManager.GetString("ProjectSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving data.
        /// </summary>
        internal static string RetrievingData {
            get {
                return ResourceManager.GetString("RetrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run reports first!.
        /// </summary>
        internal static string RunReportsFirst {
            get {
                return ResourceManager.GetString("RunReportsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes to the Accounting Information?.
        /// </summary>
        internal static string SaveChangesAccountingInformationQuestion {
            get {
                return ResourceManager.GetString("SaveChangesAccountingInformationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes to the Billing Information?.
        /// </summary>
        internal static string SaveChangesBillingInformationQuestion {
            get {
                return ResourceManager.GetString("SaveChangesBillingInformationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine.
        /// </summary>
        internal static string SearchEngine {
            get {
                return ResourceManager.GetString("SearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        internal static string Totals {
            get {
                return ResourceManager.GetString("Totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry is not a valid domain. Please try again.
        /// </summary>
        internal static string UriNotValid {
            get {
                return ResourceManager.GetString("UriNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a URL or select a file to upload.
        /// </summary>
        internal static string UrlNotEntered {
            get {
                return ResourceManager.GetString("UrlNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
