//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Navigation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Navigation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Navigation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Accounting Status Description.
        /// </summary>
        internal static string AccountingStatus_Description {
            get {
                return ResourceManager.GetString("AccountingStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Status.
        /// </summary>
        internal static string AccountingStatus_MenuLabel {
            get {
                return ResourceManager.GetString("AccountingStatus_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Status.
        /// </summary>
        internal static string AccountingStatus_Title {
            get {
                return ResourceManager.GetString("AccountingStatus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Accounting Tools Overview Description.
        /// </summary>
        internal static string AccountingToolsOverview_Description {
            get {
                return ResourceManager.GetString("AccountingToolsOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Tools Overview.
        /// </summary>
        internal static string AccountingToolsOverview_MenuLabel {
            get {
                return ResourceManager.GetString("AccountingToolsOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Tools Overview.
        /// </summary>
        internal static string AccountingToolsOverview_Title {
            get {
                return ResourceManager.GetString("AccountingToolsOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Accounting Usage Description.
        /// </summary>
        internal static string AccountingUsage_Description {
            get {
                return ResourceManager.GetString("AccountingUsage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Usage.
        /// </summary>
        internal static string AccountingUsage_MenuLabel {
            get {
                return ResourceManager.GetString("AccountingUsage_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Usage.
        /// </summary>
        internal static string AccountingUsage_Title {
            get {
                return ResourceManager.GetString("AccountingUsage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Accounting Description.
        /// </summary>
        internal static string Accounting_Description {
            get {
                return ResourceManager.GetString("Accounting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        internal static string Accounting_MenuLabel {
            get {
                return ResourceManager.GetString("Accounting_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        internal static string Accounting_Title {
            get {
                return ResourceManager.GetString("Accounting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Account Profile Description.
        /// </summary>
        internal static string AccountProfile_Description {
            get {
                return ResourceManager.GetString("AccountProfile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Profile.
        /// </summary>
        internal static string AccountProfile_MenuLabel {
            get {
                return ResourceManager.GetString("AccountProfile_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Profile.
        /// </summary>
        internal static string AccountProfile_Title {
            get {
                return ResourceManager.GetString("AccountProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Administration Tools Overview Description.
        /// </summary>
        internal static string AdministrationToolsOverview_Description {
            get {
                return ResourceManager.GetString("AdministrationToolsOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Tools Overview.
        /// </summary>
        internal static string AdministrationToolsOverview_MenuLabel {
            get {
                return ResourceManager.GetString("AdministrationToolsOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Tools Overview.
        /// </summary>
        internal static string AdministrationToolsOverview_Title {
            get {
                return ResourceManager.GetString("AdministrationToolsOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Administration Tools Description.
        /// </summary>
        internal static string AdministrationTools_Description {
            get {
                return ResourceManager.GetString("AdministrationTools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Tools.
        /// </summary>
        internal static string AdministrationTools_MenuLabel {
            get {
                return ResourceManager.GetString("AdministrationTools_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Tools.
        /// </summary>
        internal static string AdministrationTools_Title {
            get {
                return ResourceManager.GetString("AdministrationTools_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Administration Description.
        /// </summary>
        internal static string Administration_Description {
            get {
                return ResourceManager.GetString("Administration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration_MenuLabel {
            get {
                return ResourceManager.GetString("Administration_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration_Title {
            get {
                return ResourceManager.GetString("Administration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Analyze Overview Description.
        /// </summary>
        internal static string AnalyzeOverview_Description {
            get {
                return ResourceManager.GetString("AnalyzeOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Overview.
        /// </summary>
        internal static string AnalyzeOverview_MenuLabel {
            get {
                return ResourceManager.GetString("AnalyzeOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Overview.
        /// </summary>
        internal static string AnalyzeOverview_Title {
            get {
                return ResourceManager.GetString("AnalyzeOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Analyze Description.
        /// </summary>
        internal static string Analyze_Description {
            get {
                return ResourceManager.GetString("Analyze_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        internal static string Analyze_MenuLabel {
            get {
                return ResourceManager.GetString("Analyze_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        internal static string Analyze_Title {
            get {
                return ResourceManager.GetString("Analyze_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Campaigns Description.
        /// </summary>
        internal static string Campaigns_Description {
            get {
                return ResourceManager.GetString("Campaigns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        internal static string Campaigns_MenuLabel {
            get {
                return ResourceManager.GetString("Campaigns_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        internal static string Campaigns_Title {
            get {
                return ResourceManager.GetString("Campaigns_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Comparison Page Analyzer Description.
        /// </summary>
        internal static string ComparisonReport_Description {
            get {
                return ResourceManager.GetString("ComparisonReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison Page Analyzer.
        /// </summary>
        internal static string ComparisonReport_MenuLabel {
            get {
                return ResourceManager.GetString("ComparisonReport_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison Page Analyzer.
        /// </summary>
        internal static string ComparisonReport_Title {
            get {
                return ResourceManager.GetString("ComparisonReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Competitors Overview Description.
        /// </summary>
        internal static string CompetitorsOverview_Description {
            get {
                return ResourceManager.GetString("CompetitorsOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitors Overview.
        /// </summary>
        internal static string CompetitorsOverview_MenuLabel {
            get {
                return ResourceManager.GetString("CompetitorsOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitors Overview.
        /// </summary>
        internal static string CompetitorsOverview_Title {
            get {
                return ResourceManager.GetString("CompetitorsOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Comparison Page Analyzer Description.
        /// </summary>
        internal static string Competitors_Description {
            get {
                return ResourceManager.GetString("Competitors_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitors.
        /// </summary>
        internal static string Competitors_MenuLabel {
            get {
                return ResourceManager.GetString("Competitors_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitors.
        /// </summary>
        internal static string Competitors_Title {
            get {
                return ResourceManager.GetString("Competitors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Default Description.
        /// </summary>
        internal static string Default_Description {
            get {
                return ResourceManager.GetString("Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default_MenuLabel {
            get {
                return ResourceManager.GetString("Default_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default_Title {
            get {
                return ResourceManager.GetString("Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Demographics Description.
        /// </summary>
        internal static string Demographics_Description {
            get {
                return ResourceManager.GetString("Demographics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demographics.
        /// </summary>
        internal static string Demographics_MenuLabel {
            get {
                return ResourceManager.GetString("Demographics_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demographics.
        /// </summary>
        internal static string Demographics_Title {
            get {
                return ResourceManager.GetString("Demographics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: DSM Administration Description.
        /// </summary>
        internal static string DSMAdministration_Description {
            get {
                return ResourceManager.GetString("DSMAdministration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSM Administration.
        /// </summary>
        internal static string DSMAdministration_MenuLabel {
            get {
                return ResourceManager.GetString("DSMAdministration_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSM Administration.
        /// </summary>
        internal static string DSMAdministration_Title {
            get {
                return ResourceManager.GetString("DSMAdministration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: DSM Overview Description.
        /// </summary>
        internal static string DSMOverview_Description {
            get {
                return ResourceManager.GetString("DSMOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSM Overview.
        /// </summary>
        internal static string DSMOverview_MenuLabel {
            get {
                return ResourceManager.GetString("DSMOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSM Overview.
        /// </summary>
        internal static string DSMOverview_Title {
            get {
                return ResourceManager.GetString("DSMOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: DSM Report Description.
        /// </summary>
        internal static string DSMReport_Description {
            get {
                return ResourceManager.GetString("DSMReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSM Report.
        /// </summary>
        internal static string DSMReport_MenuLabel {
            get {
                return ResourceManager.GetString("DSMReport_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSM Report.
        /// </summary>
        internal static string DSMReport_Title {
            get {
                return ResourceManager.GetString("DSMReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: DSM Description.
        /// </summary>
        internal static string DSM_Description {
            get {
                return ResourceManager.GetString("DSM_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSM.
        /// </summary>
        internal static string DSM_MenuLabel {
            get {
                return ResourceManager.GetString("DSM_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSM.
        /// </summary>
        internal static string DSM_Title {
            get {
                return ResourceManager.GetString("DSM_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Employee Logs Description.
        /// </summary>
        internal static string EmployeeLogs_Description {
            get {
                return ResourceManager.GetString("EmployeeLogs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Logs.
        /// </summary>
        internal static string EmployeeLogs_MenuLabel {
            get {
                return ResourceManager.GetString("EmployeeLogs_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Logs.
        /// </summary>
        internal static string EmployeeLogs_Title {
            get {
                return ResourceManager.GetString("EmployeeLogs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Error Logs Description.
        /// </summary>
        internal static string ErrorLogs_Description {
            get {
                return ResourceManager.GetString("ErrorLogs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Logs.
        /// </summary>
        internal static string ErrorLogs_MenuLabel {
            get {
                return ResourceManager.GetString("ErrorLogs_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Logs.
        /// </summary>
        internal static string ErrorLogs_Title {
            get {
                return ResourceManager.GetString("ErrorLogs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Home Description.
        /// </summary>
        internal static string Home_Description {
            get {
                return ResourceManager.GetString("Home_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_MenuLabel {
            get {
                return ResourceManager.GetString("Home_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: HTML Sitemap Description.
        /// </summary>
        internal static string HTMLSitemap_Description {
            get {
                return ResourceManager.GetString("HTMLSitemap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Sitemap.
        /// </summary>
        internal static string HTMLSitemap_MenuLabel {
            get {
                return ResourceManager.GetString("HTMLSitemap_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Sitemap.
        /// </summary>
        internal static string HTMLSitemap_Title {
            get {
                return ResourceManager.GetString("HTMLSitemap_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Intelligence Report Description.
        /// </summary>
        internal static string IntelligenceReport_Description {
            get {
                return ResourceManager.GetString("IntelligenceReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence Report.
        /// </summary>
        internal static string IntelligenceReport_MenuLabel {
            get {
                return ResourceManager.GetString("IntelligenceReport_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence Report.
        /// </summary>
        internal static string IntelligenceReport_Title {
            get {
                return ResourceManager.GetString("IntelligenceReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Keywords Overview Description.
        /// </summary>
        internal static string KeywordsOverview_Description {
            get {
                return ResourceManager.GetString("KeywordsOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords Overview.
        /// </summary>
        internal static string KeywordsOverview_MenuLabel {
            get {
                return ResourceManager.GetString("KeywordsOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords Overview.
        /// </summary>
        internal static string KeywordsOverview_Title {
            get {
                return ResourceManager.GetString("KeywordsOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Keywords Description.
        /// </summary>
        internal static string Keywords_Description {
            get {
                return ResourceManager.GetString("Keywords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string Keywords_MenuLabel {
            get {
                return ResourceManager.GetString("Keywords_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string Keywords_Title {
            get {
                return ResourceManager.GetString("Keywords_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Link Analysis Overview Description.
        /// </summary>
        internal static string LinkAnalysisOverview_Description {
            get {
                return ResourceManager.GetString("LinkAnalysisOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Analysis Overview.
        /// </summary>
        internal static string LinkAnalysisOverview_MenuLabel {
            get {
                return ResourceManager.GetString("LinkAnalysisOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Analysis Overview.
        /// </summary>
        internal static string LinkAnalysisOverview_Title {
            get {
                return ResourceManager.GetString("LinkAnalysisOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Link Analysis Report Description.
        /// </summary>
        internal static string LinkAnalysisReport_Description {
            get {
                return ResourceManager.GetString("LinkAnalysisReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Analysis Report.
        /// </summary>
        internal static string LinkAnalysisReport_MenuLabel {
            get {
                return ResourceManager.GetString("LinkAnalysisReport_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Analysis Report.
        /// </summary>
        internal static string LinkAnalysisReport_Title {
            get {
                return ResourceManager.GetString("LinkAnalysisReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Link Analysis Description.
        /// </summary>
        internal static string LinkAnalysis_Description {
            get {
                return ResourceManager.GetString("LinkAnalysis_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Analysis.
        /// </summary>
        internal static string LinkAnalysis_MenuLabel {
            get {
                return ResourceManager.GetString("LinkAnalysis_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Analysis.
        /// </summary>
        internal static string LinkAnalysis_Title {
            get {
                return ResourceManager.GetString("LinkAnalysis_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Link Maps Overview Description.
        /// </summary>
        internal static string LinkMapsOverview_Description {
            get {
                return ResourceManager.GetString("LinkMapsOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Maps Overview.
        /// </summary>
        internal static string LinkMapsOverview_MenuLabel {
            get {
                return ResourceManager.GetString("LinkMapsOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Maps Overview.
        /// </summary>
        internal static string LinkMapsOverview_Title {
            get {
                return ResourceManager.GetString("LinkMapsOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Link Maps Description.
        /// </summary>
        internal static string LinkMaps_Description {
            get {
                return ResourceManager.GetString("LinkMaps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Maps.
        /// </summary>
        internal static string LinkMaps_MenuLabel {
            get {
                return ResourceManager.GetString("LinkMaps_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Maps.
        /// </summary>
        internal static string LinkMaps_Title {
            get {
                return ResourceManager.GetString("LinkMaps_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Link Report Description.
        /// </summary>
        internal static string LinkReport_Description {
            get {
                return ResourceManager.GetString("LinkReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Report.
        /// </summary>
        internal static string LinkReport_MenuLabel {
            get {
                return ResourceManager.GetString("LinkReport_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Report.
        /// </summary>
        internal static string LinkReport_Title {
            get {
                return ResourceManager.GetString("LinkReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Links Overview Description.
        /// </summary>
        internal static string LinksOverview_Description {
            get {
                return ResourceManager.GetString("LinksOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links Overview.
        /// </summary>
        internal static string LinksOverview_MenuLabel {
            get {
                return ResourceManager.GetString("LinksOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links Overview.
        /// </summary>
        internal static string LinksOverview_Title {
            get {
                return ResourceManager.GetString("LinksOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Links Description.
        /// </summary>
        internal static string Links_Description {
            get {
                return ResourceManager.GetString("Links_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Links_MenuLabel {
            get {
                return ResourceManager.GetString("Links_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Links_Title {
            get {
                return ResourceManager.GetString("Links_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Login Page Description.
        /// </summary>
        internal static string LoginPage_Description {
            get {
                return ResourceManager.GetString("LoginPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Page.
        /// </summary>
        internal static string LoginPage_MenuLabel {
            get {
                return ResourceManager.GetString("LoginPage_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Page.
        /// </summary>
        internal static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or edit users for the account.
        /// </summary>
        internal static string ManageAccountUsers_Description {
            get {
                return ResourceManager.GetString("ManageAccountUsers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account Users.
        /// </summary>
        internal static string ManageAccountUsers_MenuLabel {
            get {
                return ResourceManager.GetString("ManageAccountUsers_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account Users.
        /// </summary>
        internal static string ManageAccountUsers_Title {
            get {
                return ResourceManager.GetString("ManageAccountUsers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Manage Employees Description.
        /// </summary>
        internal static string ManageEmployees_Description {
            get {
                return ResourceManager.GetString("ManageEmployees_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Employees.
        /// </summary>
        internal static string ManageEmployees_MenuLabel {
            get {
                return ResourceManager.GetString("ManageEmployees_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Employees.
        /// </summary>
        internal static string ManageEmployees_Title {
            get {
                return ResourceManager.GetString("ManageEmployees_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Manage Projects Description.
        /// </summary>
        internal static string ManageProjects_Description {
            get {
                return ResourceManager.GetString("ManageProjects_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Projects.
        /// </summary>
        internal static string ManageProjects_MenuLabel {
            get {
                return ResourceManager.GetString("ManageProjects_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Projects.
        /// </summary>
        internal static string ManageProjects_Title {
            get {
                return ResourceManager.GetString("ManageProjects_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Monitor Description.
        /// </summary>
        internal static string Monitor_Description {
            get {
                return ResourceManager.GetString("Monitor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string Monitor_MenuLabel {
            get {
                return ResourceManager.GetString("Monitor_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string Monitor_Title {
            get {
                return ResourceManager.GetString("Monitor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Multi Page Analyzer Description.
        /// </summary>
        internal static string MultiPageKda_Description {
            get {
                return ResourceManager.GetString("MultiPageKda_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Page Analyzer.
        /// </summary>
        internal static string MultiPageKda_MenuLabel {
            get {
                return ResourceManager.GetString("MultiPageKda_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Page Analyzer.
        /// </summary>
        internal static string MultiPageKda_Title {
            get {
                return ResourceManager.GetString("MultiPageKda_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Optimized Pages Description.
        /// </summary>
        internal static string OptimizedPages_Description {
            get {
                return ResourceManager.GetString("OptimizedPages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized Pages.
        /// </summary>
        internal static string OptimizedPages_MenuLabel {
            get {
                return ResourceManager.GetString("OptimizedPages_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized Pages.
        /// </summary>
        internal static string OptimizedPages_Title {
            get {
                return ResourceManager.GetString("OptimizedPages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Page Analyzer Description.
        /// </summary>
        internal static string PageAnalyzer_Description {
            get {
                return ResourceManager.GetString("PageAnalyzer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Analyzer.
        /// </summary>
        internal static string PageAnalyzer_MenuLabel {
            get {
                return ResourceManager.GetString("PageAnalyzer_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Analyzer.
        /// </summary>
        internal static string PageAnalyzer_Title {
            get {
                return ResourceManager.GetString("PageAnalyzer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Partner Tools Overview Description.
        /// </summary>
        internal static string PartnerToolsOverview_Description {
            get {
                return ResourceManager.GetString("PartnerToolsOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Tools Overview.
        /// </summary>
        internal static string PartnerToolsOverview_MenuLabel {
            get {
                return ResourceManager.GetString("PartnerToolsOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Tools Overview.
        /// </summary>
        internal static string PartnerToolsOverview_Title {
            get {
                return ResourceManager.GetString("PartnerToolsOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Partner Tools Description.
        /// </summary>
        internal static string PartnerTools_Description {
            get {
                return ResourceManager.GetString("PartnerTools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Tools.
        /// </summary>
        internal static string PartnerTools_MenuLabel {
            get {
                return ResourceManager.GetString("PartnerTools_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Tools.
        /// </summary>
        internal static string PartnerTools_Title {
            get {
                return ResourceManager.GetString("PartnerTools_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Path Maps Overview Description.
        /// </summary>
        internal static string PathMapsOverview_Description {
            get {
                return ResourceManager.GetString("PathMapsOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Maps Overview.
        /// </summary>
        internal static string PathMapsOverview_MenuLabel {
            get {
                return ResourceManager.GetString("PathMapsOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Maps Overview.
        /// </summary>
        internal static string PathMapsOverview_Title {
            get {
                return ResourceManager.GetString("PathMapsOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Path Maps Report Description.
        /// </summary>
        internal static string PathMapsReport_Description {
            get {
                return ResourceManager.GetString("PathMapsReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Maps Report.
        /// </summary>
        internal static string PathMapsReport_MenuLabel {
            get {
                return ResourceManager.GetString("PathMapsReport_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Maps Report.
        /// </summary>
        internal static string PathMapsReport_Title {
            get {
                return ResourceManager.GetString("PathMapsReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Path Maps Settings Description.
        /// </summary>
        internal static string PathMapsSettings_Description {
            get {
                return ResourceManager.GetString("PathMapsSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Maps Settings.
        /// </summary>
        internal static string PathMapsSettings_MenuLabel {
            get {
                return ResourceManager.GetString("PathMapsSettings_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Maps Settings.
        /// </summary>
        internal static string PathMapsSettings_Title {
            get {
                return ResourceManager.GetString("PathMapsSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Pathmaps Description.
        /// </summary>
        internal static string Pathmaps_Description {
            get {
                return ResourceManager.GetString("Pathmaps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathmaps.
        /// </summary>
        internal static string Pathmaps_MenuLabel {
            get {
                return ResourceManager.GetString("Pathmaps_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathmaps.
        /// </summary>
        internal static string Pathmaps_Title {
            get {
                return ResourceManager.GetString("Pathmaps_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Pixelsilk Description.
        /// </summary>
        internal static string Pixelsilk_Description {
            get {
                return ResourceManager.GetString("Pixelsilk_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixelsilk.
        /// </summary>
        internal static string Pixelsilk_MenuLabel {
            get {
                return ResourceManager.GetString("Pixelsilk_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixelsilk.
        /// </summary>
        internal static string Pixelsilk_Title {
            get {
                return ResourceManager.GetString("Pixelsilk_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Potential Traffic Description.
        /// </summary>
        internal static string PotentialTraffic_Description {
            get {
                return ResourceManager.GetString("PotentialTraffic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential Traffic.
        /// </summary>
        internal static string PotentialTraffic_MenuLabel {
            get {
                return ResourceManager.GetString("PotentialTraffic_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential Traffic.
        /// </summary>
        internal static string PotentialTraffic_Title {
            get {
                return ResourceManager.GetString("PotentialTraffic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Put the Title for the Dashboard.
        /// </summary>
        internal static string Project_Dashboard_Description {
            get {
                return ResourceManager.GetString("Project_Dashboard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Dashboard.
        /// </summary>
        internal static string Project_Dashboard_MenuLabel {
            get {
                return ResourceManager.GetString("Project_Dashboard_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Dashboard.
        /// </summary>
        internal static string Project_Dashboard_Title {
            get {
                return ResourceManager.GetString("Project_Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Project Description.
        /// </summary>
        internal static string Project_Description {
            get {
                return ResourceManager.GetString("Project_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project_MenuLabel {
            get {
                return ResourceManager.GetString("Project_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project_Title {
            get {
                return ResourceManager.GetString("Project_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Ranked Keywords Description.
        /// </summary>
        internal static string RankedKeywords_Description {
            get {
                return ResourceManager.GetString("RankedKeywords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked Keywords.
        /// </summary>
        internal static string RankedKeywords_MenuLabel {
            get {
                return ResourceManager.GetString("RankedKeywords_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked Keywords.
        /// </summary>
        internal static string RankedKeywords_Title {
            get {
                return ResourceManager.GetString("RankedKeywords_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the settings for your project’s Ranking Monitor and schedule how often it automatically runs.
        /// </summary>
        internal static string RankingMonitorConfiguration_Description {
            get {
                return ResourceManager.GetString("RankingMonitorConfiguration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Monitor.
        /// </summary>
        internal static string RankingMonitorConfiguration_MenuLabel {
            get {
                return ResourceManager.GetString("RankingMonitorConfiguration_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Monitor.
        /// </summary>
        internal static string RankingMonitorConfiguration_Title {
            get {
                return ResourceManager.GetString("RankingMonitorConfiguration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A summary of the latest Ranking Monitor run for the selected project.
        /// </summary>
        internal static string RankingMonitorDashboard_Description {
            get {
                return ResourceManager.GetString("RankingMonitorDashboard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Dashboard.
        /// </summary>
        internal static string RankingMonitorDashboard_MenuLabel {
            get {
                return ResourceManager.GetString("RankingMonitorDashboard_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Dashboard.
        /// </summary>
        internal static string RankingMonitorDashboard_Title {
            get {
                return ResourceManager.GetString("RankingMonitorDashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the data from a Ranking Monitor, or compare two Ranking Monitor reports from different dates.
        /// </summary>
        internal static string RankingMonitorReports_Description {
            get {
                return ResourceManager.GetString("RankingMonitorReports_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reports.
        /// </summary>
        internal static string RankingMonitorReports_MenuLabel {
            get {
                return ResourceManager.GetString("RankingMonitorReports_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reports.
        /// </summary>
        internal static string RankingMonitorReports_Title {
            get {
                return ResourceManager.GetString("RankingMonitorReports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor your pages’ search engine rankings for your selected keywords.
        /// </summary>
        internal static string RankingMonitorRun_Description {
            get {
                return ResourceManager.GetString("RankingMonitorRun_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Monitor.
        /// </summary>
        internal static string RankingMonitorRun_MenuLabel {
            get {
                return ResourceManager.GetString("RankingMonitorRun_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Monitor.
        /// </summary>
        internal static string RankingMonitorRun_Title {
            get {
                return ResourceManager.GetString("RankingMonitorRun_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Relationship Chart Description.
        /// </summary>
        internal static string RelationshipChart_Description {
            get {
                return ResourceManager.GetString("RelationshipChart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Chart.
        /// </summary>
        internal static string RelationshipChart_MenuLabel {
            get {
                return ResourceManager.GetString("RelationshipChart_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Chart.
        /// </summary>
        internal static string RelationshipChart_Title {
            get {
                return ResourceManager.GetString("RelationshipChart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Research Summary Description.
        /// </summary>
        internal static string ResearchSummary_Description {
            get {
                return ResourceManager.GetString("ResearchSummary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Summary.
        /// </summary>
        internal static string ResearchSummary_MenuLabel {
            get {
                return ResourceManager.GetString("ResearchSummary_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Summary.
        /// </summary>
        internal static string ResearchSummary_Title {
            get {
                return ResourceManager.GetString("ResearchSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Schedule Processes Description.
        /// </summary>
        internal static string ScheduleProcesses_Description {
            get {
                return ResourceManager.GetString("ScheduleProcesses_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Processes.
        /// </summary>
        internal static string ScheduleProcesses_MenuLabel {
            get {
                return ResourceManager.GetString("ScheduleProcesses_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Processes.
        /// </summary>
        internal static string ScheduleProcesses_Title {
            get {
                return ResourceManager.GetString("ScheduleProcesses_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Search User Or Account Description.
        /// </summary>
        internal static string SearchUserOrAccount_Administrator_Description {
            get {
                return ResourceManager.GetString("SearchUserOrAccount_Administrator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User Or Account.
        /// </summary>
        internal static string SearchUserOrAccount_Administrator_MenuLabel {
            get {
                return ResourceManager.GetString("SearchUserOrAccount_Administrator_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User Or Account.
        /// </summary>
        internal static string SearchUserOrAccount_Administrator_Title {
            get {
                return ResourceManager.GetString("SearchUserOrAccount_Administrator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Search User Or Account Description.
        /// </summary>
        internal static string SearchUserOrAccount_Description {
            get {
                return ResourceManager.GetString("SearchUserOrAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User Or Account.
        /// </summary>
        internal static string SearchUserOrAccount_MenuLabel {
            get {
                return ResourceManager.GetString("SearchUserOrAccount_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User Or Account.
        /// </summary>
        internal static string SearchUserOrAccount_Title {
            get {
                return ResourceManager.GetString("SearchUserOrAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Sign Up Description.
        /// </summary>
        internal static string SignUp_Description {
            get {
                return ResourceManager.GetString("SignUp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp_MenuLabel {
            get {
                return ResourceManager.GetString("SignUp_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp_Title {
            get {
                return ResourceManager.GetString("SignUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Single Page Analyzer Description.
        /// </summary>
        internal static string SinglePageKda_Description {
            get {
                return ResourceManager.GetString("SinglePageKda_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Page Analyzer.
        /// </summary>
        internal static string SinglePageKda_MenuLabel {
            get {
                return ResourceManager.GetString("SinglePageKda_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Page Analyzer.
        /// </summary>
        internal static string SinglePageKda_Title {
            get {
                return ResourceManager.GetString("SinglePageKda_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Site Checker Description.
        /// </summary>
        internal static string SiteChecker_Description {
            get {
                return ResourceManager.GetString("SiteChecker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Checker.
        /// </summary>
        internal static string SiteChecker_MenuLabel {
            get {
                return ResourceManager.GetString("SiteChecker_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Checker.
        /// </summary>
        internal static string SiteChecker_Title {
            get {
                return ResourceManager.GetString("SiteChecker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Site Information Description.
        /// </summary>
        internal static string SiteInformation_Description {
            get {
                return ResourceManager.GetString("SiteInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Information.
        /// </summary>
        internal static string SiteInformation_MenuLabel {
            get {
                return ResourceManager.GetString("SiteInformation_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Information.
        /// </summary>
        internal static string SiteInformation_Title {
            get {
                return ResourceManager.GetString("SiteInformation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Site Link Spider Description.
        /// </summary>
        internal static string SiteLinkSpider_Description {
            get {
                return ResourceManager.GetString("SiteLinkSpider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Link Spider.
        /// </summary>
        internal static string SiteLinkSpider_MenuLabel {
            get {
                return ResourceManager.GetString("SiteLinkSpider_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Link Spider.
        /// </summary>
        internal static string SiteLinkSpider_Title {
            get {
                return ResourceManager.GetString("SiteLinkSpider_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Sitemaps XML Generator Description.
        /// </summary>
        internal static string SitemapsXMLGenerator_Description {
            get {
                return ResourceManager.GetString("SitemapsXMLGenerator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemaps XML Generator.
        /// </summary>
        internal static string SitemapsXMLGenerator_MenuLabel {
            get {
                return ResourceManager.GetString("SitemapsXMLGenerator_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemaps XML Generator.
        /// </summary>
        internal static string SitemapsXMLGenerator_Title {
            get {
                return ResourceManager.GetString("SitemapsXMLGenerator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Stopword Editor Description.
        /// </summary>
        internal static string StopwordEditor_Description {
            get {
                return ResourceManager.GetString("StopwordEditor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopword Editor.
        /// </summary>
        internal static string StopwordEditor_MenuLabel {
            get {
                return ResourceManager.GetString("StopwordEditor_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopword Editor.
        /// </summary>
        internal static string StopwordEditor_Title {
            get {
                return ResourceManager.GetString("StopwordEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Submission Pages Description.
        /// </summary>
        internal static string SubmissionPages_Description {
            get {
                return ResourceManager.GetString("SubmissionPages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Pages.
        /// </summary>
        internal static string SubmissionPages_MenuLabel {
            get {
                return ResourceManager.GetString("SubmissionPages_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Pages.
        /// </summary>
        internal static string SubmissionPages_Title {
            get {
                return ResourceManager.GetString("SubmissionPages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Submit Overview Description.
        /// </summary>
        internal static string SubmitOverview_Description {
            get {
                return ResourceManager.GetString("SubmitOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Overview.
        /// </summary>
        internal static string SubmitOverview_MenuLabel {
            get {
                return ResourceManager.GetString("SubmitOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Overview.
        /// </summary>
        internal static string SubmitOverview_Title {
            get {
                return ResourceManager.GetString("SubmitOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Submit Description.
        /// </summary>
        internal static string Submit_Description {
            get {
                return ResourceManager.GetString("Submit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit_MenuLabel {
            get {
                return ResourceManager.GetString("Submit_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit_Title {
            get {
                return ResourceManager.GetString("Submit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Subscriber Or Account List Description.
        /// </summary>
        internal static string SubscriberOrAccountList_Administrator_Description {
            get {
                return ResourceManager.GetString("SubscriberOrAccountList_Administrator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber Or Account List.
        /// </summary>
        internal static string SubscriberOrAccountList_Administrator_MenuLabel {
            get {
                return ResourceManager.GetString("SubscriberOrAccountList_Administrator_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber Or Account List.
        /// </summary>
        internal static string SubscriberOrAccountList_Administrator_Title {
            get {
                return ResourceManager.GetString("SubscriberOrAccountList_Administrator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Subscribers Or Accounts List Description.
        /// </summary>
        internal static string SubscribersOrAccountsList_Description {
            get {
                return ResourceManager.GetString("SubscribersOrAccountsList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers Or Accounts List.
        /// </summary>
        internal static string SubscribersOrAccountsList_MenuLabel {
            get {
                return ResourceManager.GetString("SubscribersOrAccountsList_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers Or Accounts List.
        /// </summary>
        internal static string SubscribersOrAccountsList_Title {
            get {
                return ResourceManager.GetString("SubscribersOrAccountsList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Suggested Keywords Description.
        /// </summary>
        internal static string SuggestedKeywords_Description {
            get {
                return ResourceManager.GetString("SuggestedKeywords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Keywords.
        /// </summary>
        internal static string SuggestedKeywords_MenuLabel {
            get {
                return ResourceManager.GetString("SuggestedKeywords_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Keywords.
        /// </summary>
        internal static string SuggestedKeywords_Title {
            get {
                return ResourceManager.GetString("SuggestedKeywords_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Support Tools Overview Description.
        /// </summary>
        internal static string SupportToolsOverview_Description {
            get {
                return ResourceManager.GetString("SupportToolsOverview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Tools Overview.
        /// </summary>
        internal static string SupportToolsOverview_MenuLabel {
            get {
                return ResourceManager.GetString("SupportToolsOverview_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Tools Overview.
        /// </summary>
        internal static string SupportToolsOverview_Title {
            get {
                return ResourceManager.GetString("SupportToolsOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Support Tools Description.
        /// </summary>
        internal static string SupportTools_Description {
            get {
                return ResourceManager.GetString("SupportTools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Tools.
        /// </summary>
        internal static string SupportTools_MenuLabel {
            get {
                return ResourceManager.GetString("SupportTools_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Tools.
        /// </summary>
        internal static string SupportTools_Title {
            get {
                return ResourceManager.GetString("SupportTools_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Tools Description.
        /// </summary>
        internal static string Tools_Description {
            get {
                return ResourceManager.GetString("Tools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools_MenuLabel {
            get {
                return ResourceManager.GetString("Tools_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools_Title {
            get {
                return ResourceManager.GetString("Tools_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Traffic Checker Description.
        /// </summary>
        internal static string TrafficChecker_Description {
            get {
                return ResourceManager.GetString("TrafficChecker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Checker.
        /// </summary>
        internal static string TrafficChecker_MenuLabel {
            get {
                return ResourceManager.GetString("TrafficChecker_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Checker.
        /// </summary>
        internal static string TrafficChecker_Title {
            get {
                return ResourceManager.GetString("TrafficChecker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Transfer Account Data Description.
        /// </summary>
        internal static string TransferAccountData_Administrator_Description {
            get {
                return ResourceManager.GetString("TransferAccountData_Administrator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Account Data.
        /// </summary>
        internal static string TransferAccountData_Administrator_MenuLabel {
            get {
                return ResourceManager.GetString("TransferAccountData_Administrator_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Account Data.
        /// </summary>
        internal static string TransferAccountData_Administrator_Title {
            get {
                return ResourceManager.GetString("TransferAccountData_Administrator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Transfer Acount Data Description.
        /// </summary>
        internal static string TransferAcountData_Description {
            get {
                return ResourceManager.GetString("TransferAcountData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Acount Data.
        /// </summary>
        internal static string TransferAcountData_MenuLabel {
            get {
                return ResourceManager.GetString("TransferAcountData_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Transfer Acount Data Description.
        /// </summary>
        internal static string TransferAcountData_Support_Description {
            get {
                return ResourceManager.GetString("TransferAcountData_Support_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Acount Data.
        /// </summary>
        internal static string TransferAcountData_Support_MenuLabel {
            get {
                return ResourceManager.GetString("TransferAcountData_Support_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Acount Data.
        /// </summary>
        internal static string TransferAcountData_Support_Title {
            get {
                return ResourceManager.GetString("TransferAcountData_Support_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Acount Data.
        /// </summary>
        internal static string TransferAcountData_Title {
            get {
                return ResourceManager.GetString("TransferAcountData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Trending Reports Description.
        /// </summary>
        internal static string TrendingReports_Description {
            get {
                return ResourceManager.GetString("TrendingReports_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending Reports.
        /// </summary>
        internal static string TrendingReports_MenuLabel {
            get {
                return ResourceManager.GetString("TrendingReports_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending Reports.
        /// </summary>
        internal static string TrendingReports_Title {
            get {
                return ResourceManager.GetString("TrendingReports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Trending Report Description.
        /// </summary>
        internal static string TrendingReport_Description {
            get {
                return ResourceManager.GetString("TrendingReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending Report.
        /// </summary>
        internal static string TrendingReport_MenuLabel {
            get {
                return ResourceManager.GetString("TrendingReport_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending Report.
        /// </summary>
        internal static string TrendingReport_Title {
            get {
                return ResourceManager.GetString("TrendingReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Upload Link List Description.
        /// </summary>
        internal static string UploadLinkList_Description {
            get {
                return ResourceManager.GetString("UploadLinkList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Link List.
        /// </summary>
        internal static string UploadLinkList_MenuLabel {
            get {
                return ResourceManager.GetString("UploadLinkList_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Link List.
        /// </summary>
        internal static string UploadLinkList_Title {
            get {
                return ResourceManager.GetString("UploadLinkList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: User Profile Description.
        /// </summary>
        internal static string UserProfile_Description {
            get {
                return ResourceManager.GetString("UserProfile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string UserProfile_MenuLabel {
            get {
                return ResourceManager.GetString("UserProfile_MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string UserProfile_Title {
            get {
                return ResourceManager.GetString("UserProfile_Title", resourceCulture);
            }
        }
    }
}
